infrastructureDefinition:
  name: owaspzap
  identifier: owaspzap
  orgIdentifier: default
  projectIdentifier: default_project
  environmentRef: harnessdevenv
  deploymentType: Kubernetes
  type: KubernetesAws
  spec:
    connectorRef: awseks
    cluster: us-east-2/space-proj-poc
    namespace: default
    releaseName: release-<+INFRA_KEY_SHORT_ID>
    provisioner: <+input>
    region: us-east-2
  allowSimultaneousDeployments: true
